Added code of daily Coding Exercise -9
anushreeSonak/DemoRepo pull request #14
Opened 2023-05-11 07:31 UTC by anushreeSonak

2023-05-12 10:39 UTC, amitsahu8 requested changes

2023-05-12 10:39 UTC, amitsahu8 commented on First/dailyExercises/PrintEvenLength.java
> +        String s = "I am Anushree sonak and I am from kothrud pune";
Please follow coding guidelines

2023-05-15 05:47 UTC, anushreeSonak commented on First/dailyExercises/PrintEvenLength.java
> +        String s = "I am Anushree sonak and I am from kothrud pune";
Done !

2023-05-15 06:00 UTC, amitsahu8 requested changes

2023-05-15 06:00 UTC, amitsahu8 commented on First/dailyExercises/PrintEvenLength.java
> +        for (String word : s.split(" "))
please don't use single character variable name

2023-05-15 06:12 UTC, anushreeSonak commented on First/dailyExercises/PrintEvenLength.java
> +        for (String word : s.split(" "))
Done !!

2023-05-15 10:21 UTC, amitsahu8 approved these changes

2023-05-15 10:21 UTC, merged