Added code of daily Coding Exercise-12
anushreeSonak/DemoRepo pull request #17
Opened 2023-05-18 08:41 UTC by anushreeSonak

2023-05-18 09:18 UTC, amitsahu8 requested changes

2023-05-18 09:18 UTC, amitsahu8 commented on First/dailyExercises/ReverseLetters.java
> +        String[] arrayData = mockData.split(" ");
no need of split

2023-05-18 09:18 UTC, amitsahu8 commented on First/dailyExercises/ReverseLetters.java
> +            for (int subIndex = letter.length - 1; subIndex >= 0; subIndex--) {
no need of nested for loop

2023-05-22 07:22 UTC, anushreeSonak commented on First/dailyExercises/ReverseLetters.java
> +        String[] arrayData = mockData.split(" ");
DONE !

2023-05-22 07:22 UTC, anushreeSonak commented on First/dailyExercises/ReverseLetters.java
> +            for (int subIndex = letter.length - 1; subIndex >= 0; subIndex--) {
DONE !

2023-05-22 09:08 UTC, amitsahu8 approved these changes

2023-05-22 09:08 UTC, merged